version: '3'

services:

  db:
    container_name: db
    build: ./images/db
    volumes: 
      - ./db/magento2:/var/lib/mysql
    environment:
      MAGE2_DB_NAME: magento2
      MAGE2_DB_CLIENT_NAME: root 
      MAGE2_DB_CLIENT_AUTH: 
      MAGE2_DB_ROOT_AUTH: 

  mage2:
    container_name: mage2 
    build: ./images/mage2
    volumes:
      - ./htdocs/magento2:/var/www/html
    ports:
      - 8081:80

